--[[ ---------------------------------------------
 File       : mod_use_callback.script
 Description: Колбеки на использование предметов
 Author     : denis2000#sigerous.ru
-------------------------------------------------]]

local active_slot = nil
local active_item_name = nil
local binoc_in_slot = nil
local name_binoc = nil
---------------------------------------------------------------------------
--Вызов колбеков использования предметов инвентаря
---------------------------------------------------------------------------
function use_inventory_item(section,self)
	local item_name=section:section()
	active_slot=db.actor:active_slot()
	binoc_in_slot=db.actor:item_in_slot(5)
	if binoc_in_slot ~= nil then
		name_binoc = binoc_in_slot:section()
	end
    		
   --Использован предмет Хлеб, в данный момент не используется другой анимационный предмет
   if item_name=="bread" and db.actor:has_info("actor_use_anm_item") == false then
		--Удалить бинокль у ГГ
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		--Дать анимационный объект Хлеб
		alife():create("anm_bread",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		--Проверка, что ГГ назодиться в зоне без оружия
		if self.weapon_hide == true then
			--Позволить достать оружие
			self.object:restore_weapon()
			-- и выставить флаг, что по оканчании анимации оружие спрятать
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		--Сделать слот с Хлебом активным
		db.actor:activate_slot(5)
		--Проиграть звук использования Хлеба с задержкой.
		snd = sound_object([[interface\inv_food]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		--Задать интервал времени и установить флаги используем Хлеб и используем анимационный предмет
		db.actor:give_info_portion("actor_use_anm_bread")
		db.actor:give_info_portion("actor_use_anm_item")
		--Установить засечку начала анимации предмета
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Аптечка, в данный момент не используется другой анимационный предмет
   if string.find(item_name,"medkit") and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		--Проверка типа аптечки
		if item_name=="medkit" then
			alife():create("anm_medkit",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		elseif item_name=="medkit_army" then
			alife():create("anm_medkit_army",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		elseif item_name=="medkit_scientic" then
			alife():create("anm_medkit_scientic",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		end
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_medkit]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_medkit")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Колбаса, в данный момент не используется другой анимационный предмет
	if item_name=="kolbasa" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_kolbasa",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_food]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_kolbasa")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Энергетик, в данный момент не используется другой анимационный предмет
	if item_name=="energy_drink" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_energy_drink",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_softdrink]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_energy_drink")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Тушенка, в данный момент не используется другой анимационный предмет
	if item_name=="conserva" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_conserva",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_food]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_conserva")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Вакцина, в данный момент не используется другой анимационный предмет
	if item_name=="antirad" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_antirad",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_pills]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_antirad")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Водка, в данный момент не используется другой анимационный предмет
	if item_name=="vodka" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_vodka",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_vodka]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_vodka")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	--Использован предмет Вода, в данный момент не используется другой анимационный предмет
	if item_name=="voda" and db.actor:has_info("actor_use_anm_item") == false then
		if name_binoc == "wpn_binoc" then
			alife():release(alife():object(db.actor:object("wpn_binoc"):id()))
		end
		alife():create("anm_voda",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		if self.weapon_hide == true then
			self.object:restore_weapon()
			db.actor:give_info_portion("use_item_need_hide_weapon")
		end
		db.actor:activate_slot(5)
		snd = sound_object([[interface\inv_vodka]])
		snd:play_at_pos(db.actor, vector():set(0,0,0), 2, sound_object.s2d) --Третий параметр время задержки воспроизведения в сек
		db.actor:give_info_portion("actor_use_anm_voda")
		db.actor:give_info_portion("actor_use_anm_item")
		start_time_use_item = game.get_game_time()
	end
	
end

---------------------------------------------------------------------------
--Отработка таймеров использования предметов
---------------------------------------------------------------------------
function timer_use_item(self)
	local time_to_use_bread = 23 --Игровые секунды, время использования предмета Хлеб
	local time_to_use_medkit = 23 --Игровые секунды, время использования предмета Аптечка
	local time_to_use_kolbasa = 30 --Игровые секунды, время использования предмета Колбаса
	local time_to_use_energy_drink = 25 --Игровые секунды, время использования предмета Энергетик
	local time_to_use_conserva = 35 --Игровые секунды, время использования предмета Тушенка
	local time_to_use_antirad = 30 --Игровые секунды, время использования предмета Антирад
	local time_to_use_vodka = 30 --Игровые секунды, время использования предмета Водка
	local time_to_use_voda = 30 --Игровые секунды, время использования предмета Вода
	local time_to_relax = 10 --Игровые секунды, время переключения после использования предмета
	local release_item = nil
	--Отработка таймеров использования предметов
	if db.actor:has_info("actor_use_anm_item") then
		--Отработка таймера для Хлеба
		if  db.actor:has_info("actor_use_anm_bread") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_bread) then
			--Переключиться на старый слот
			db.actor:activate_slot(active_slot)
			--Установить флаг таймаута после использования предмета
			db.actor:give_info_portion("use_item_relax")
			--Снять флаг используем Хлеб
			db.actor:disable_info_portion("actor_use_anm_bread")
			--Если нужно снова прятать оружие
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				--Прячем его с установкой переменных 
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			--Cбросо флага "по оканчании анимации оружие спрятать"
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			--Установить засечку начала таймаута после использования предмета
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Аптечки
		if  db.actor:has_info("actor_use_anm_medkit") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_medkit) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_medkit")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Колбаса
		if  db.actor:has_info("actor_use_anm_kolbasa") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_kolbasa) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_kolbasa")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Энергетик
		if  db.actor:has_info("actor_use_anm_energy_drink") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_energy_drink) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_energy_drink")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Тушенка
		if  db.actor:has_info("actor_use_anm_conserva") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_conserva) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_conserva")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Антирад
		if  db.actor:has_info("actor_use_anm_antirad") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_antirad) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_antirad")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Водка
		if  db.actor:has_info("actor_use_anm_vodka") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_vodka) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_vodka")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймера для Вода
		if  db.actor:has_info("actor_use_anm_voda") and (start_time_use_item == nil or game.get_game_time():diffSec(start_time_use_item) >= time_to_use_voda) then
			db.actor:activate_slot(active_slot)
			db.actor:give_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_voda")
			if db.actor:has_info("use_item_need_hide_weapon") and self.weapon_hide == true then
				self.object:hide_weapon()
				self.weapon_hide = true
			end
			db.actor:disable_info_portion("use_item_need_hide_weapon")
			start_time_relax = game.get_game_time()
		end
		--Отработка таймеров таймаута после использования предметов
		if db.actor:has_info("use_item_relax") and (start_time_relax == nil or game.get_game_time():diffSec(start_time_relax) >= time_to_relax) then
			--Убрать из инвентаря анимационный предмет, каким бы он ни был
			db.actor:iterate_inventory(function (dummy, item) if string.find(item:section(), "anm_") then release_item = item:section() end end, nil)
			alife():release(alife():object(db.actor:object(release_item):id()))
			--Вернуть бинокль в инвентарь
			--[[if binoc_in_slot ~= nil and name_binoc ~= nil then
				if db.actor:object(name_binoc) == nil then
					alife():create(name_binoc,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
				end
			end]]
			if db.actor:object("wpn_binoc") == nil then
				alife():create("wpn_binoc",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
			end
			--Сбросить флаги использования предметов и таймаута после использования предмета
			db.actor:disable_info_portion("use_item_relax")
			db.actor:disable_info_portion("actor_use_anm_item")
		end
	end
	--Обработка взрывчатки
	local time_to_use_explosive_charge = 10 --Игровые секунды, время использования предмета взрывчатка
	local time_to_use_explosive_control = 20 --Игровые секунды, время использования предмета ДУ
	local actor_pos=db.actor:position()
	--Устанавливаем одину и только одну взрывчатку
	if db.actor:has_info("actor_set_remote_explosive_charge") 
	and db.actor:has_info("actor_set_one_remote_explosive_charge") == false then
		if (start_time_explosive_charge == nil 
		or game.get_game_time():diffSec(start_time_explosive_charge) >= time_to_use_explosive_charge) then
		--Установить взывающийся объект
		mod_functions.create_explosive_on_level("remote_charge",actor_pos.x,actor_pos.y,actor_pos.z+0.01,db.actor:level_vertex_id(),db.actor:game_vertex_id())
		--Удалить заряд из инвентаря
		alife():release(alife():object(db.actor:object("anm_remote_explosive_charge"):id()))
		--Выдать инфопорцию о том что один заряд заложен
		db.actor:give_info_portion("actor_set_one_remote_explosive_charge")
		end
	end
	--Взорвать установленную взрывчатку
	if db.actor:has_info("actor_activate_remote_explosive_control") then
		if (start_time_explosive_control == nil 
		or game.get_game_time():diffSec(start_time_explosive_control) >= time_to_use_explosive_control) then
		--Взорвать взывающийся объект
		mod_functions.detonate_explosive(mod_functions.read_variable("remote_charge_id"))
		mod_functions.write_variable("remote_charge_id",0)
		--Удалить ДУ-актив из инвентаря
		alife():release(alife():object(db.actor:object("anm_remote_explosive_control"):id()))
		--Забрать инфопорцию о включении ДУ
		db.actor:disable_info_portion("actor_activate_remote_explosive_control")
		--Забрать инфопорцию о установке заряда взрывчатки
		db.actor:disable_info_portion("actor_set_remote_explosive_charge")
		--Забрать инфопорцию о том что один заряд заложен
		db.actor:disable_info_portion("actor_set_one_remote_explosive_charge")
		end
	end
end

---------------------------------------------------------------------------------------------------------------------------------
--Вызов колбеков на отсутствие патронов интерактивные предметы
---------------------------------------------------------------------------------------------------------------------------------
function weapon_no_ammo()
	active_slot = db.actor:active_slot()
	active_item_name = db.actor:item_in_slot(active_slot):section()
	--news_manager.send_tip(db.actor, "Активный слот "..tostring(active_slot).." Активный предмет "..tostring(active_item_name), nil, nil, nil, nil)
	--Нажата кнопка при использовании заряда взрывчатки
	if active_item_name == "anm_remote_explosive_charge" then
		--Если у ГГ есть ДУ-неакт или нет уже установленной взрывчатки или ДУ уже включено
		if db.actor:object("ammo_remote_explosive_charge") ~= nil 
		and db.actor:has_info("actor_set_remote_explosive_charge") == false 
		and db.actor:has_info("actor_activate_remote_explosive_control") == false
		and db.actor:has_info("actor_set_one_remote_explosive_charge") == false	then
			--Удалить ДУ-Неактивированный
			alife():release(alife():object(db.actor:object("ammo_remote_explosive_charge"):id()))
			--Дать анимационный объект ДУ-активированный
			alife():create("anm_remote_explosive_control",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
			--Выдать инфопорцию о установке заряда взрывчатки
			db.actor:give_info_portion("actor_set_remote_explosive_charge")
			--Установить засечку начала анимации установки взрывчатки
			start_time_explosive_charge = game.get_game_time()
		else
			get_hud():HideActorMenu()
			get_hud():HidePdaMenu()
			game.start_tutorial("about_actor_no_explosive_charge")
			--Установить активный слот 5
			db.actor:activate_slot(5)
		end
	end
	if active_item_name == "anm_remote_explosive_control" then
		--Если у ГГ есть батарея для ДУ или ДУ уже включено
		if db.actor:object("ammo_remote_explosive_control") ~= nil and db.actor:has_info("actor_activate_remote_explosive_control") == false then
			--Удалить Батарею для ДУ
			alife():release(alife():object(db.actor:object("ammo_remote_explosive_control"):id()))
			--Выдать инфопорцию о включении ДУ
			db.actor:give_info_portion("actor_activate_remote_explosive_control")
			--Установить засечку начала анимации включения ДУ
			start_time_explosive_control = game.get_game_time()
		else
			get_hud():HideActorMenu()
			get_hud():HidePdaMenu()
			game.start_tutorial("about_actor_no_explosive_control")
			--Установить активный слот 5
			db.actor:activate_slot(5)
		end
	end
end

