function has_flyga_empety(task, objective) 
if db.actor ~= nil then
return db.actor:object("flask_empty") ~= nil
end
return false
end

function has_money_water(actor, npc)
	return actor:money() >= 150
end

function give_flyga_with_water(first_speaker, second_speaker)
    dialogs.relocate_item_section(second_speaker, "flask", "in")
    dialogs.relocate_item_section(first_speaker, "flask_empty", "out")
    dialogs.relocate_money(first_speaker, 150, "out")
end